orlandos-nl/MongoKitten

Sources/Server.swift
The int16value is making for really weird results.
=> fix port error

Sources/MongoKitten/QueryBuilder.swift, Tests/MongoKittenTests/CollectionTests.swift
Allow to pass options to query for example case insensitivity
=> add options for contains query

Sources/MongoSocket/Socket.swift
Fixes https://github.com/OpenKitten/MongoKitten/issues/143
@Joannis @Obbut
=> [Issue 143]: SNI Hostname Memory leak

Sources/MongoKitten/AdministrativeQueries.swift, Sources/MongoKitten/Cluster.swift, Sources/MongoKitten/Commands/FindCommand.swift, Sources/MongoKitten/Commands/ListCollections.swift, Sources/MongoKitten/Commands/ListDatabases.swift, Sources/MongoKitten/Commands/Namespace.swift, Sources/MongoKitten/Cursor.swift, Sources/MongoKitten/Database.swift, Tests/MongoKittenTests/CRUDTests.swift
Adds `listCollections` to Database and `listDatabases` to Cluster
=> Implement list databases/collections on cluster

README.md
Added Vapor 3 specific usage
People needed a Vapor 3 example
No need
=> Added Vapor 3 clarity

Sources/MongoKitten/AggregateStage.swift
=> support the .match(query)

Sources/MongoKitten/Aggregate.swift, Sources/MongoKitten/AggregateBuilder.swift, Sources/MongoKitten/AggregateStage.swift
There should be some code documentation. I would suggest to find a common style for doing this, so I started with adding some documentation. Please feel free to comment.
=> WIP: first start of adding some documentation

Sources/MongoCore/Primitives/Namespace.swift, Sources/MongoKitten/CollectionHelpers/Collection+Indexes.swift, Tests/MongoCoreTests/ProtocolTests.swift
Added the ability to list indexes from a collection.
It's not, but it should be. I'd like to refer to #228 for now.
=> List indexes

Sources/MongoKitten/CollectionHelpers/Collection+Indexes.swift
This PR adds a new `createIndexes` function that accepts an array of indexes to allow more flexibility.
More customization on the type of index a user might want to create.
Doesn't really need to, it's just an extension of an existing function.
=> Add a new createIndexes function for more flexibility and customization

Sources/MongoClient/Cluster.swift
=> Thread sanitizer fix for disconnecting a cluster

Sources/MongoClient/Cluster.swift
=> When disconnecting the cluster, flush the list of connected hostnames

Sources/MongoKitten/CollectionHelpers/Collection+Distinct.swift, Tests/MongoKittenTests/CRUDTests.swift
Fix use of query inside DistinctCommand inside distinctValues function
Add unit test
=> Use provide Query for distinctValues request

Sources/MongoClient/Cluster.swift
Provides the same support for custom eventloopgroups that MK6 has. As per this issue: https://forums.swift.org/t/how-to-connect-to-mongodb-using-an-existing-multithreadedeventloopgroup/59052
=> Allow users to provide their own eventloopgroup in a cluster's initializer

Sources/Meow/Indexes.swift, Sources/Meow/MeowCollection.swift, Sources/Meow/Model.swift, Sources/MongoKitten/CollectionHelpers/Collection+Indexes.swift, Sources/MongoKitten/IndexBuilder.swift, Tests/MeowTests/MeowTests.swift, Tests/MongoKittenTests/CRUDTests.swift
@Joannis This problem probably also arises in 7.0 but I will test this soon.
=> upsert-success check fails

Sources/MongoKitten/MongoDatabase.swift, Tests/MongoKittenTests/TransactionTests.swift
=> add logger

Sources/MongoClient/Cluster.swift, Sources/MongoClient/Connection.swift, Sources/MongoClient/MongoSingleConnectionPool.swift, Sources/MongoKitten/MongoDatabase.swift
Updates the logger labels to the new org.
Consistency
=> Update logger label

Sources/Meow/Documentation.docc/Meow.md
swift-biome can link the ``MongoCollection`` symbol link.
=> link `MongoCollection`

Sources/MongoClient/Cluster.swift
Closes #310, as already discussed with @Joannis 
Adding a test case to catch this would be a good idea, but is quite involved, so I will create another issue for that.
=> Fix a race condition in MongoCluster

Package.swift, Sources/Meow/Migrations.swift, Sources/MongoClient/Channel+Connection.swift
- Replaces some print statements by logging to a logger
- Pin the DNSClient build
=> Some small fixes

Sources/_MongoKittenCrypto/MD5.swift, Sources/_MongoKittenCrypto/PBKDF2.swift, Sources/_MongoKittenCrypto/SHA1.swift, Sources/_MongoKittenCrypto/SHA256.swift, Tests/MongoCoreTests/ProtocolTests.swift, Tests/MongoKittenTests/CryptoPerformanceTests.swift, Tests/MongoKittenTests/CryptoTests.swift
This is a cherry pick of #315 to the 6.0 branch.
=> Speed up use of PBKDF2 when building in Debug configuration (6.x cherry-pick)

Sources/Meow/Database.swift
Fixed 2 typos.
For better docs.
Human spell checker :)
=> Fix typos in Docs
