Sources/MongoKitten/QueryBuilder.swift, Tests/MongoKittenTests/CollectionTests.swift
- Added the query operators `.contains`, `.startsWith`, `.endsWith` (which only work with Strings)
- Main goal was to get closer parity to Vapor operators.
- ~~Needs tests~~
=> Operators:  `.contains`, `.startsWith`, `.endsWith`

Sources/MongoKitten/QueryBuilder.swift
Fixes issue #76.
Permits creation of more complicated queries like:
```
[
"documents": [ 
"$elemMatch": [ 
"value": "1234" 
] 
] 
]
```
=> Added support for $elementMatch

Sources/MongoKitten/Database.swift
When trying to use MONGODB-CR authentication I found that it didn't work. After some investigation I found that the call to `self.execute` would result in indefinitely recursion into authentication. `self.execute -> server.reserveConnection -> connection.authenticate`.
By not using `"\(digest.hexString)"`, but `"\(digest)"` it would serialize the wrong representation of the digest.
After finally solving the authentication (it appeared to work), I found that my server version was not supported (2.4) so I gave up.
=> Fix MONGODB-CR authentication

README.md
Update the `README.md` to refer to IBM Cloud instead of Bluemix.
=> docs: Bluemix is now IBM Cloud

README.md
Updates the link and name for IBM Cloud in the README's *Set up MongoDB*, so users can quickly get started with MongoDB & MongoKitten.
This change replaces a stale link in the README to the MongoDB service.
IBM Cloud rebranded from its former Bluemix name last summer, and the link here was not relevant to MongoKitten users looking to provision MongoDB.
=> IBM Cloud rebrand

Sources/MongoKitten/Database.swift
Added initializer to connect to a database with ConnectionSettings parameter
Before you were only allowed to synchronously connect to MongoKitten.Database using a uri, making you only be able to connect to insecure mongo instance. Now we can pass in ConnectionSettings so we can activate ssl, use credentials and etc.
The motivation lies in the need to be able to set the environment variables of a MongoKitten.Database environment when synchronously connecting to the database. By being able to activate ssl, authentication, number of connections and other parameters included in ConnectionSettings, we can do that. Before this pull request, you were unable to do this if you are in non-NIO environment.
Tested local scripts using this method and it works.
=> Added initializer to connect to a database with ConnectionSettings parameter

Sources/GridFS/FileWriter.swift
This fixes an issue with GridFS writes that require more than one chunk. The chunk number was not being correctly incremented.
=> Increment the nextChunkNumber

Sources/MongoKitten/Commands/UpdateCommand.swift, Sources/MongoKitten/Index.swift
Adding the MongoDB array update operators.
MongoDB provides several operators for updating arrays on documents. The solution proposes a very similar architecture to the existing UpdateOperator enum.
The change will provide more type safety and feels more swifty. 
The Operators provide for easier discoverability.
Single test for $push, working fine.
No further tests, yet.
=> Add array update operators

Sources/MongoKitten/AggregateBuilder.swift, Sources/MongoKitten/Commands/AggregateCommand.swift
To perform uncorrelated subqueries between two collections as well as allow other join conditions besides a single equality match, the $lookup stage has the following syntax:
```
{
$lookup:
{
from: <collection to join>,
let: { <var_1>: <expression>, …, <var_n>: <expression> },
pipeline: [ <pipeline to execute on the collection to join> ],
as: <output array field>
}
}
```
I refacto the `AggregateCursor`, I extract all function needed to construct an aggregate command, I extract them to a new protocol `AggregateBuilder`, And  I conform `AggreagteCursor` to AggregateBuilder. I did this to be able to reuse function that build an aggreagate command (like match, limit, lookup...). And I implement the new lookup to perform uncorrelated subqueries between two collections as well as allow other …
=> feat: implement lookup with subQueries

Sources/MongoKitten/AggregateBuilder.swift, Sources/MongoKitten/AggregateStage.swift
Added helper support for the `$addFields` pipeline stage.
Having a convenient helper similar to `match` and `sort` for a common pipeline stage seems helpful
It hasn't
=> Added helper support for the $addFields pipeline stage.

Sources/MongoKittenCore/Commands/Update.swift
Modified the UpdateCommand.UpdateRequest struct to include the upsert variable in the CodingKeys enum.
Performing an upsert operation with a document that does not exist in the collection does not insert the document.
https://github.com/OpenKitten/MongoKitten/issues/215
Tested locally.
=> Add the upsert variable to the CodingKeys.

Sources/MongoKitten/Connection.swift, Sources/MongoKitten/ConnectionSettings.swift
The --sslCA (trust root certificate) is required to connect to AWS DocumentDB.
Added an option to provide a path to root certificate as part of SSL setting.
=> added --sslCA(mongo client) parameter equivalent for MongoKitten

Sources/MongoKitten/AggregateBuilder.swift, Sources/MongoKitten/AggregateStage.swift
Added `$unwind` and `$replaceRoot` `AggregateBuilderStage`s.
This PR adds support for the `$replaceRoot` aggregate stage and adds missing support for `$unwind` to function builder syntax.
It compiles and although these APIs are straight forward, there are no unit tests to verify document output.
=> Added $unwind and $replaceRoot AggregateBuilderStages.

Sources/MongoKitten/Aggregate.swift, Sources/MongoKitten/CollectionHelpers/Collection+Count.swift, Sources/MongoKitten/CollectionHelpers/Collection+Delete.swift, Sources/MongoKitten/CollectionHelpers/Collection+Distinct.swift, Sources/MongoKitten/CollectionHelpers/Collection+Find.swift, Sources/MongoKitten/CollectionHelpers/Collection+Insert.swift, Sources/MongoKitten/CollectionHelpers/Collection+Update.swift, Sources/MongoKitten/MongoDatabase.swift, Sources/MongoKitten/MongoTransactionDatabase.swift, Tests/MongoCoreTests/ProtocolTests.swift
1. Creating a new decode function to be used with findOne() similar to the one already existing and which works with find(). this new decode transforms an EventLoopFuture<Document?> to EventLoopFuture<Codable?> eg:return r.db["CollectionName"].findOne(query).decode(Codable.self).
2. Renaming an existing decode function to "decodeReply" in order to solve naming conflict
3. Address some minor warning
=> New decode function for findOne()

Sources/MongoClient/Connection+Execute.swift, Sources/MongoClient/Connection.swift
=> Dispatch all queries on the EventLoop thread to prevent the access of the MongoKittenContext from different threads

Sources/MongoKitten/AggregateBuilder.swift, Sources/MongoKitten/AggregateStage.swift
This PR adds support for the [`$geoNear`](https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/) aggregate stage
This adds more missing API to aggregate stages.
=> Added geoNear aggregate stage.

Sources/MongoKitten/CollectionHelpers/Collection+FindAndModify.swift
Adds a helpful `decode()` function the the `FindAndModifyQueryBuilder`
This helps making these commands cleaner and more in line with the cursor based API.
So we can go from this :
```swift
findOneAndUpdate(where: "_id" == ObjectId(),
to: ["$set": ["field": "value"]],
returnValue: .modified)
.execute()
.map(\.value)
.decode(PayoutDetailsResponse.self)
```
To this:
```swift
findOneAndUpdate(where: "_id" == ObjectId(),
to: ["$set": ["field": "value"]],
returnValue: .modified)
.decode(PayoutDetailsResponse.self)
```
=> Added decoder helper.

Sources/Meow/AsyncAwait.swift, Sources/Meow/MeowCollection.swift, Sources/MongoKitten/AsyncAwait.swift, Sources/MongoKitten/CollectionHelpers/Collection+Delete.swift, Sources/MongoKitten/CollectionHelpers/Collection+Insert.swift, Tests/MongoKittenTests/CRUDTests.swift
This PR adds support for specifying a `write concern`  when performing insert commands.
This makes it easier to add a write concern using the collection convenience APIs vs constructing an `InsertCommand` manually and manually executing it.
=> Added write concern support for insert APIs.

Package.swift
[BSON 7.0.0 has build issues in Swift 5.5 that are resolved in 7.0.28](https://github.com/orlandos-nl/BSON/issues/69).  I bumped the minimum version of BSON so that SPM will not potentially resolve package version that will cause MongoKitten to fail to build on newer versions of Swift.
I was following [this raywenderlich.com tutorial](https://www.raywenderlich.com/10521463-server-side-swift-with-mongodb-getting-started) and the starter project failed to build.  This is a tough onboarding experience for people who are learning.  After I did some research and discovered the source of the issue (a default protocol conformance marked unavailable in Swift 5.5) and that the issue had been fixed already in BSON, I figured I would try to make the onboarding experience easier for the next …
=> Require version 7.0.28 of BSON to avoid Swift 5.5 build errors

Sources/MongoClient/Connection.swift, Sources/MongoClient/MongoSingleConnectionPool.swift
we must manually inline [`MongoConnection.authenticate(clientDetails:using:to:)`](https://swiftinit.org/reference/mongokitten/mongoclient/mongoconnection.authenticate%28clientdetails:using:to:%29) into [`MongoSingleConnectionPool.next(for:)`](https://swiftinit.org/reference/mongokitten/mongoclient/mongosingleconnectionpool.next%28for:%29) due to the llvm coroutine splitting issue https://github.com/apple/swift/issues/60380. 
this could also be accomplished by adding `@inline(never)` to `MongoConnection.authenticate(clientDetails:using:to:)`, but this preserves the runtime behavior more closely.
=> implement workaround for compiler crash #60380

.github/workflows/swift.yml, Package.swift, Sources/MongoClient/Cluster.swift, Sources/MongoClient/Connection.swift, Sources/MongoCore/Sessions.swift, Sources/MongoKitten/MongoDatabase.swift, Tests/MongoKittenTests/TransactionTests.swift, docker-compose.yaml, scripts/setup.sh
Adds tests around transactions
There's 2 tests, 1 for testing a transaction while inserting data into 2 separate collections.
and the second test is doing the same while still on the same connection.
This is happening on MongoDB V5
Have been seeing crashes when running back to back transactions and this adds tests around that area. But in adding the tests, this test case breaks because the connection pool can't seem to determine the max wire version.
=> Adds test for transaction.

Sources/_MongoKittenCrypto/MD5.swift, Sources/_MongoKittenCrypto/PBKDF2.swift, Sources/_MongoKittenCrypto/SHA1.swift, Sources/_MongoKittenCrypto/SHA256.swift, Tests/MeowTests/MeowTests.swift, Tests/MongoCoreTests/ProtocolTests.swift, Tests/MongoKittenTests/CryptoPerformanceTests.swift, Tests/MongoKittenTests/CryptoTests.swift
MongoKitten users (including those using the Fluent 4 driver built on it) sometimes experience significant connection delays during development due to the compiler not optimizing the PBKDF2 implementation. With a little help from Instruments, these delays can be massively reduced. The follow shows a timing comparison between the original code and that provided in this PR:
10,000 iterations of each hash are repeated 10x, and the total times averaged. Each test is run in Debug and Release configurations, against the original and revised implementations. The first number is the runtime average of the original code; the second number is the runtime average of the new code. The third number expresses how much of the original implementation's runtime is used by the revised one. …
=> Speed up use of PBKDF2 when building in Debug configuration

Sources/MongoClient/Cluster.swift
Uses port specified in an `SRVRecord` instead of overwriting the port from initial `ConnectionSettings.Host.port` value.
When `mongodb+srv//` scheme is used to connect to a database it uses default port number `27017`. Hosts resolved from the service might use arbitrary port numbers. Using default port to connect to hosts leads to connection error.
I successfully connected to database via `mongodb+srv//` scheme that resolved hosts requiring specific port number.
=> Uses port from SRVRecord

Package.swift
replaces the `exact` version requirement for DNSClient with a `from` requirement, as described in #331 .
=> replace the `exact` version requirement for DNSClient with a `from` requirement

Sources/MongoClient/Cursor.swift, Sources/MongoKitten/ChangeStream.swift
Currently, ChangeStreams require the `.forEach` method for iteration. This PR makes iterating possible through `for try await change in changeStream` syntax.
This PR also adds a cancellationHandler in `Cursor.getMore` because change streams could be kept open potentially indefinitely while waiting for more data. This can prolong the lifetime of a change stream _well_ beyond expected.
=> Allow iterating through a change stream

Sources/Meow/KeyPathModel/KeyPathModels.swift, Tests/MeowTests/MeowTests.swift
Adds support for updating `PrimitiveEncodable` fields in a `makePartialUpdate` block.
linked issue #342
=> added support for PrimitiveEncodable in ModelUpdater

Sources/Meow/Database.swift
`MeowDatabase` is not marked as sendable, potentially resulting in warnings with complete concurrency checking.
Added `@unchecked Sendable` annotation, because it is modeled as a non-final class. Otherwise it should be perfectly fine.
=> Mark MeowDatabase as Sendable

Sources/MongoKitten/AggregateStage.swift
Fix the header doc typo of `Project` stage, add simple `Group` stage implementation.
- Using `Group` in Aggregate builder
- Fix confuse header doc
Used it to query a real db.
=> Support aggregate `Group`, fix header doc typo

Package.swift, Package@swift-5.9.swift, Package@swift-6.0.swift
This PR updates the DNSClient dependency from version 2.2.1 to 2.4.2 to resolve Sendable protocol conformance requirements in Cluster.swift.
The current version of DNSClient (2.2.1) lacks Sendable protocol conformance, causing compilation errors in `Cluster.swift`. 
-  #350
- Verified successful compilation with Swift 5.9+
=> Upgrade DNSClient from 2.2.1 to 2.4.2

Sources/Meow/KeyPathModel/KeyPathModels.swift, Sources/Meow/Reference.swift
Added Sendable conformance to Field and Reference types for improved thread safety and compatibility with concurrent Swift contexts:
- #352
This change ensures compatibility with `Sendable` requirements in Swift's concurrency model, addressing thread-safety concerns for asynchronous use cases. No breaking changes are introduced.  
- Manual testing of affected structures in a concurrent environment to ensure proper `Sendable` behavior.
- Reviewed usage of `Field` and `Reference` types to confirm no adverse impact on existing functionality.
=> Add Sendable Conformance to Field and Reference Types

Sources/MongoKitten/Aggregate.swift
Adds `.batchSize()` method to `AggregateBuilderPipeline` to provide API consistency with `FindQueryBuilder`.
Currently, `FindQueryBuilder` has a `.batchSize()` method that controls initial batch size, but `AggregateBuilderPipeline` lacks this functionality. This creates inconsistent pagination behavior where find queries can set consistent page sizes from the first batch, while aggregations always use MongoDB's default initial batch size (~101 docs).
- Add `_batchSize: Int?` property to store batch size
- Add `batchSize(_ batchSize: Int)` method following existing API patterns
- Update `makeCommand()` to set `command.cursor.batchSize`
- `Sources/MongoKitten/Aggregate.swift`: Add batchSize functionality
```swift
let pipeline = collection.buildAggregate {
Match(where: "status" == "active") …
```
=> Add batchSize() method to AggregateBuilderPipeline for API consistency [WIP]
